; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc1-n16r8]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino
; upload_protocol = espota
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = partitions.csv
board_build.extra_flags = 
	-DBOARD_HAS_PSRAM
build_flags = 
	-std=gnu++2a
	-fno-exceptions
	-Wall
	-Wextra
	-O2
	-fdiagnostics-color=always
	-DCORE_DEBUG_LEVEL=3
	-std=gnu++20
build_unflags = -std=gnu++11
extra_scripts = pre:copy_glcdfont.py
board_build.f_cpu = 240000000L
board_build.filesystem = spiffs
board_build.spiffs.max_filename_len = 64
lib_deps =
	adafruit/Adafruit GFX Library@^1.12.3
	adafruit/Adafruit ILI9341@^1.6.2
	adafruit/RTClib@^2.1.4
	adafruit/Adafruit NeoPixel@^1.15.4
	; bitbank2/PNGdec@^1.0.5  -- zastąpiono przez raw RGB565 binary
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
upload-port = COM5
